### ISSUE TITLE
Build and execution instructions for Linux

### ISSUE THREAD

**Issue by benalexau** [shanecastle/IbContractExtractor#7]
Thanks Shane for continuing this project on GitHub.

The following notes detail how to build and execute IBContractExtractor on Linux. Please feel free to put these in the readme or close the ticket if preferred.

## Prerequisites
Install Mono using your distribution's package manager. The following was tested with Mono 5.0.0.

## Compilation
`pushd source && xbuild && popd`

## Execution
`mono source/bin/Debug/IbExtract.exe`

**Comment by shanecastle** [comment]
Thanks, will do.
